/*
 * generated by Xtext
 */
package org.lunifera.metamodel.dsl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.lunifera.metamodel.dsl.ui.internal.SqlDSLActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SqlDSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return SqlDSLActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return SqlDSLActivator.getInstance().getInjector(SqlDSLActivator.ORG_LUNIFERA_METAMODEL_DSL_SQLDSL);
	}
	
}
