/*
* generated by Xtext
*/
package org.lunifera.metamodel.dsl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class SqlDSLUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.lunifera.metamodel.dsl.ui.internal.SqlDSLActivator.getInstance().getInjector("org.lunifera.metamodel.dsl.SqlDSL");
	}
	
}
