/*
* generated by Xtext
*/
package org.lunifera.metamodel.dsl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.lunifera.metamodel.dsl.services.SqlDSLGrammarAccess;

public class SqlDSLParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private SqlDSLGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.lunifera.metamodel.dsl.parser.antlr.internal.InternalSqlDSLParser createParser(XtextTokenStream stream) {
		return new org.lunifera.metamodel.dsl.parser.antlr.internal.InternalSqlDSLParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "SModel";
	}
	
	public SqlDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(SqlDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
