/*
 * generated by Xtext
 */
package org.lunifera.metamodel.dsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SqlDSLRuntimeModule extends org.lunifera.metamodel.dsl.AbstractSqlDSLRuntimeModule {

}
