/*
 * generated by Xtext
 */
package org.lunifera.metamodel.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SqlDSLUiModule extends org.lunifera.metamodel.dsl.ui.AbstractSqlDSLUiModule {
	public SqlDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
