/*
* generated by Xtext
*/
package org.lunifera.metamodel.dsl.ui.contentassist;

import org.lunifera.metamodel.dsl.ui.contentassist.AbstractSqlDSLProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class SqlDSLProposalProvider extends AbstractSqlDSLProposalProvider {

}
